# Generated by Django 4.2.10 on 2024-07-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecovolontyor',
            name='img',
            field=models.ImageField(upload_to='media/volontyor'),
        ),
        migrations.AlterField(
            model_name='edokon',
            name='img',
            field=models.ImageField(upload_to='media/edokon'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(upload_to='media/news'),
        ),
    ]
